apiVersion: apps/v1
kind: Deployment

metadata:
  name: springboot-cicd-poc

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: springboot-cicd-poc

  template:
    metadata:
      labels:
        app: springboot-cicd-poc

    spec:
      containers:
        - name: springboot-cicd-poc

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}